### ISSUE TITLE
Not possible to choose right article at "Das Rheintal"

### ISSUE THREAD

**Issue by sandoxy** [machiav3lli/DerDieDas#10]
When the word "Rheintal" appears and you choose correctly "Das", then "Das" turnes red and no "correct" altetnative blinks in green. When the next time you choose another article, then the chosen(wrong) article turnes red and "Das" blinks in green. There is no possebility to coninue at that point.

**Comment by machiav3lli** [comment]
Fixed, but unfortunately with upcoming release (having some nice new features) you'll have to start over.

**Comment by machiav3lli** [comment]
2.0.0 already up:
https://github.com/machiav3lli/DerDieDas/releases/tag/2.0.0
