### ISSUE TITLE
After update to 2.0 stats shows all words fully learned

### ISSUE THREAD

**Issue by sandoxy** [machiav3lli/DerDieDas#11]
The error above occured after the update to 2.0. As long as you do not press the stats button, you can play the game. After pressing the stats button the app shows all words as fully learned and it is not possible to continue playing. After every reinstall the same issue.

**Comment by machiav3lli** [comment]
I guess this is connected to #12 & #13. I'll check it next week

**Comment by sandoxy** [comment]
After last update: when you klick the wrong article, it turnes red and the right article blincks green. When you then accidently klick the blincking green article, the app says, that all nouns are fully learned.

**Comment by machiav3lli** [comment]
Oh, I'll check it soon enough. Sorry for the incovenience somethings are right now, but as I don't have a community to do the testing after me refactoring huge portions of the code, it'll take couple of releases for it to be stable again

**Comment by bleetsheep** [comment]
> as I don't have a community to do the testing after me refactoring huge portions of the code, it'll take couple of releases for it to be stable again

Totally fine but that would have been good to know beforehand, so I can backup the data directory before updating. I am using this tool seriously and now all progress from the past few months is gone, which is rather frustrating.

**Comment by machiav3lli** [comment]
@bleetsheep I agree, it wasn't well thought and I repeat my sorry for that. For the future, I'll be posting two versions:
- normal with the same package name as till now
- test version with ".neo" as a suffix in the package name (like I do for OABX, so I don't know if I'll be publishing it on FDroid/IzzyOnDroid)

And maybe will start a small testing group on Telegram or Matrix.
