### ISSUE TITLE
"Uhr" = "clock" or "watch", not "hour"

### ISSUE THREAD

**Issue by UniqueActive** [machiav3lli/DerDieDas#19]
Hello, I just noticed a mistranslation on your otherwise great app! The translation link in the Readme did not work, so I am reporting it here.

"Die Uhr" is translated in the app as "Hour" but the correct translation should be "Clock" or "Watch". I am native German and various dictionaries seem to agree too. :)

"Die Stunde" would be the correct word for "hour".

**Comment by machiav3lli** [comment]
Yeah, seems like the project "vanished" from weblate for some reason. Thanks for the correction.

Most of the translations to english that I've done till now happend after midnight, so yeah, some mistranslations or mistakes (like Schule that's translated to: Schule) :)

I'll correct those in the upcoming days.

**Comment by UniqueActive** [comment]
No problem, you can let me know once it is working again (or alternatively which file contains the strings) and I would happily take a look too and send patches :)
