### ISSUE TITLE
Remove Dutch Belgium translation

### ISSUE THREAD

**Issue by PanderMusubi** [machiav3lli/DerDieDas#25]
Please, remove empty Dutch Belgium translation from Weblate. Dutch in general covers the Netherlands, Suriname and Belgium.

![Screenshot_20220521-010738_Fennec](https://user-images.githubusercontent.com/198964/169623256-8e21016a-57f3-4093-ae36-18d5884608be.png)

**Comment by machiav3lli** [comment]
Actually it's not added, but Weblate is suggesting you to add it.

**Comment by PanderMusubi** [comment]
I had a discussion with the creator of Webkate at FOSDEM a few years back. It should not suggest it, since translation will be identical in 99.99% of the cases. To save translation efkrt, please remove it.

**Comment by machiav3lli** [comment]
@PanderMusubi I guess you misunderstood/didn't comprehend what I've said, so here with more details:
The Belgium variation is not created, you only see a suggestion on your side to add it. [Here's](https://user-images.githubusercontent.com/40302595/171149579-94bb34a9-d702-4b57-9c54-20e100c7cea4.png) how it looks in the "reality" (for non-users) and - for comparison - [here](https://user-images.githubusercontent.com/40302595/171149889-7b468a17-2015-440b-912e-668b28bf8506.png) how it looks to me logged in.

**Comment by PanderMusubi** [comment]
Ah, thanks. No way to prevent that suggestion from showing?

**Comment by machiav3lli** [comment]
All I can do on my side is blocking users from adding new languages (which isn't a solution really), so maybe you gotta change your user settings to have only non-regional Dutch as a suggestion
