### ISSUE TITLE
Suggestion: show correct article in front of the word when tapping der/die/das

### ISSUE THREAD

**Issue by hamoid** [machiav3lli/DerDieDas#27]
I believe it could help those of us with visual memory to see the article appear in front of the word when we tap one of the three options. 

Currently the noun (above) and the article (below) are separated, which is fine while we think about it.

Once I tap an article, I pronounce (and hear) the correct version,  but I would also like to **see** the correct version in the screen to save it in my visual memory.

**Comment by machiav3lli** [comment]
Fine idea!
