### ISSUE TITLE
Dutch translation not visible

### ISSUE THREAD

**Issue by mvhulten** [machiav3lli/DerDieDas#29]
I am running 2.1.0 from F-Droid.

In the app's settings the Dutch translation is not available.  Other languages that have a smaller part of the words translated are available.

Could the Dutch translation made available, or is the fact I don't see it a bug?

**Comment by machiav3lli** [comment]
I didn't do release since a while, maybe it was added newly since the last release, I'll see if I can squeeze one in the next days.

**Comment by mvhulten** [comment]
I would appreciate that a lot!  At least for Dutch, learning German words through English translations is a roundabout way to learn German.

**Comment by machiav3lli** [comment]
Just merged, and will be released in the next hours
