### ISSUE TITLE
Untranslated words

### ISSUE THREAD

**Issue by mvhulten** [machiav3lli/DerDieDas#30]
What happens if a word is not translated?  Wil it not present at all?  This seems to be the case based on my statistical test with Norwegian (15 % translated): the first thirty words or so have translations.

I *suppose* this is the best, if only because there must surely be homonyms that are only disambiguated by gender.  Is that the case?

I am asking because during translation I was inclined to not translate words that are idential (except for case), like *Hotel* which is *hotel* in Dutch.  It not showing up in the app means fewer letters on the screen, less distraction.  WDYT?

**Comment by machiav3lli** [comment]
English is the fallback option, so when a word isn't translated, the english word will be shown.

**Comment by mvhulten** [comment]
Apropos, I noticed my recent translations are not included in the latest release.  But changes are committed from Weblate, so I do not understand what happened.
