### ISSUE TITLE
Only first 1200 words on Weblate

### ISSUE THREAD

**Issue by mvhulten** [machiav3lli/DerDieDas#35]
DerDieDas has 9963 words (`app/src/main/res/raw/list_nouns.txt`).  On Weblate are only the first 1200 words.  Why is that?

**Comment by machiav3lli** [comment]
I move and translate the words manually (usually à 100 words). I didn't translate much since a while.
If you're welling to help, I can provide you with some pointers helping ease the process.

**Comment by mvhulten** [comment]
Yes, pointers appreciated.
Weblate works alright, but if can translate in a local editor, that may be more efficient for me.

First 1200 may actually be sufficient for the next few months.

**Comment by mvhulten** [comment]
You may add a couple hundred more.

Besides the English translations not being of very high quality, the Dutch is of really poor quality, often getting the sense of the word wrong.  Were they automatically translated from the English translation?  That would explain it.

**Comment by mvhulten** [comment]
The Dutch translations on the German Wiktionary are good, as far as I can see.  Many words are not translated at all, but at least I'd have something reliable to start with.

There is [an API](https://de.wiktionary.org/w/api.php) and I might give it a go using the [Wiktionary::Parser](https://metacpan.org/pod/Wiktionary::Parser) package (which might need changes).

It may be best to fill in the remaining untranslated words manually, using a good dictionary.  I am using *Wahrig Deutsches Wörterbuch* as my main authorative source here.

**Comment by mvhulten** [comment]
When going through the first 1200 words, I found that manual labour is needed in any case to really be confident about your translations.  Even though the automation idea may be educational/fun, it may not be that useful for this purpose, or at least not the way I preliminarily planned to do it.  I might put that on the shelf for now.

If and when words are added to Weblate, I'll probably translate some more into Dutch (as that is the language most useful for me, and the words are often similar to German).

**Comment by machiav3lli** [comment]
I think this can be closed for now, I'll see if I can slip a release in my full schedule those next weeks.
