### ISSUE TITLE
Meter is almost always masculine nowadays

### ISSUE THREAD

**Issue by asquiart** [machiav3lli/DerDieDas#38]
https://de.m.wiktionary.org/wiki/Meter

**Comment by mvhulten** [comment]
This would also be true for *Kilometer*, *Quadratmeter* and *Zentimeter* (all the other *meter* words in DerDieDas).

**Comment by asquiart** [comment]
Yes you are right @mvhulten. I have found many more words that are wrong.

In the case of meter the word is used mainly for different things in German and English.
Meter in German mainly means the measuring unit, where as far as i understood meter in English is a measuring device most of the time. Booth meanings are valid in both languages but in German they have different genders

I am currently trying to extend the wiktionary scraper to allow for multiple meanings and/or genders.
