### ISSUE TITLE
Change misleading colors

### ISSUE THREAD

**Issue by m-rey** [machiav3lli/DerDieDas#4]
Please change the answer bg color from the current red/reddish color to something like green. Using red to show the _correct_ option is quite confusing. Users that have tried the app thought they selected the wrong answer, when in reality they chose the correct one.

Using a color that is associated with "correct" instead, like green, would solve this issue. 

screenshots:
![dark](https://github.com/machiav3lli/DerDieDas/raw/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png) 
![light](https://github.com/machiav3lli/DerDieDas/raw/master/fastlane/metadata/android/en-US/images/phoneScreenshots/4.png)

**Comment by machiav3lli** [comment]
Will change on next release

**Comment by muchuelo** [comment]
After reading this I am confused. In F-Droid it says "blue for correct answers" and "red for wrong answers" (v1.2.0)

**Comment by muchuelo** [comment]
Now I understand what's going on. The F-Droid description is wrong. Red currently indicates a correct answer, which as already pointed out is counter intuitive. 
Please change to green for correct and red for wrong. And update F-Droid dscription. (But I appreciate the F-Droid update delay factor).
