### ISSUE TITLE
Text mis-aligned in boxes

### ISSUE THREAD

**Issue by muchuelo** [machiav3lli/DerDieDas#5]
![Der Die Das](https://user-images.githubusercontent.com/76464195/111558156-86b44900-878e-11eb-81a3-05e4d3df7768.png)

Screenshot attached. Samsung Galaxy S4 Mini. Android 7.1.2

**Comment by machiav3lli** [comment]
Seems a problem on screens with low dpi/ppi. Will take care of in the next release.
