### ISSUE TITLE
Confused about flashing red

### ISSUE THREAD

**Issue by muchuelo** [machiav3lli/DerDieDas#6]
When clicking on "Die" for "Samstag", " Die" turns solid blue (according to description on F-Droid this indicates a correct answer) but at the same time, "Der" flashes red several times. This is what happens wih all words - one box lights up blue and one, or sometimes both the other buttons flash red. It's very confusing.

**Comment by machiav3lli** [comment]
Duplicate to #4, the problem stems from #2. As in #4 stated, colors will be changed as soon as I have time to.
