### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by muchuelo** [machiav3lli/DerDieDas#7]
Humbly suggest changing the icon for one that does not make the app look like a system app.

**Comment by muchuelo** [comment]
![Der-Die-Das-Icon-small (1)](https://user-images.githubusercontent.com/76464195/111902144-3235f580-8a3c-11eb-8f31-c252521553e3.jpg)

Felt inclined to do something creative.
Feel free to use this, if you like it.

**Comment by muchuelo** [comment]
I can send you the image file. (I'm seeing a thin black line at the top of the image here. That is not present in the file.

**Comment by muchuelo** [comment]
Here are a couple of alternatives

![Der-Die-Das-Icon-small (1) square rotate](https://user-images.githubusercontent.com/76464195/111903637-97411980-8a43-11eb-978d-470dde188523.jpg)


![Der-Die-Das-Icon-small (1) square rotate-2](https://user-images.githubusercontent.com/76464195/111903651-a9bb5300-8a43-11eb-96e8-501f4a355f51.jpg)

**Comment by machiav3lli** [comment]
I don't know if it's that obvious, but the logo has three Ds. I understand that there's much going in the logo and I'd like to make it simpler, when I have time. One thing that I don't want is binding the language to a flag, as it's spoken elsewhere e.g. Austria, like you can maybe already see in the current logo.

**Comment by muchuelo** [comment]
Well, have now updated app from F-Droid. Thanks for the improvements. I see what you mean about the logo. It is very busy and hard to make out, but at least it's distinctive and no longer looks like a system app. It makes sense not binding it to a single flag/country.

Anyway, it's a useful app. A good supplement to my regular language-learning app. Always finish off my daily sessions with a few minutes of Der Die Das.

**Comment by bleetsheep** [comment]
Don't know what it was before, but fwiw I like the current logo!

**Comment by machiav3lli** [comment]
Updated on [latest Release](https://github.com/machiav3lli/DerDieDas/releases/tag/2.1.1)
