### ISSUE TITLE
Spanish locale

### ISSUE THREAD

**Issue by caralu74** [machiav3lli/DerDieDas#8]
Warm greetings!
Can be added a Spanish translation for the GUI?

**Comment by machiav3lli** [comment]
Yeah, you can gladly translate the strings file and I'll add it. Or just wait for me to get the project on Weblate.

**Comment by caralu74** [comment]
Thanks!
Sorry, but Where are the strings or .po or .xlif file? and Are there a list of all the words?

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by caralu74** [comment]
I´ve found the list. (in 
DerDieDas/app/src/main/res/raw/
)

**Comment by machiav3lli** [comment]
Link to the translation platform added in the README:
https://hosted.weblate.org/engage/derdiedas/
