### ISSUE TITLE
APK at release 1.2.1 has wrong versionName (and -Code?)

### ISSUE THREAD

**Issue by IzzySoft** [machiav3lli/DerDieDas#9]
The APK attached to release 1.2.1 identifies as 1.2.0:

    package: name='com.machiav3lli.derdiedas' versionCode='1200' versionName='1.2.0'

Looks like that affects `versionCode` as well, so it won't be considered an update by Android. Can you please replace it with a fixed one? Thanks!

**Comment by machiav3lli** [comment]
Oh, I'll correct it soon enough with 2.0.0. It's actually just that I forgot to change version before building.

**Comment by machiav3lli** [comment]
2.0.0 already up:
https://github.com/machiav3lli/DerDieDas/releases/tag/2.0.0

**Comment by IzzySoft** [comment]
Yupp, updater says it looks fine – thanks!
